### ISSUE TITLE
On mobile

### ISSUE THREAD

**Issue by belauzas** [undefinedCudaCore/My-Portfolio#1]
- padaryti, jog scroll'iinant neišsiskleistu meniu
- išdydinti šriftus / elementus
- ir turbūt daugiau mažiau viską pateikti vienu stulpeliu

Tiesa, gali būti, jog tinkamai įkėlus projektą (ne per iframe), dauguma klaidų gali savaime dingti.

**Comment by undefinedCudaCore** [comment]
Done
